name: Node.js Contineous Integration

on:
  push:
    branches: ["main"]

    tags:
      - "v*"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{secrets.MONGODB_URI}}

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ["5.0"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Integration test
        run: npm run integrationtest
