name: Node.js Contineous Integration

on:
  push:
    branches: ["main"]

    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Installing all dev dependencis & integration tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

        env:
          CI: true
          MONGODB_URI: ${{ secrets.MONGODB_URI}}
      # - name: Connect to DB
      #   uses: supercharge/mongodb-github-action@1.8.0
      #   with:
      #     MONGODB_URI: ${{ secrets.MONGODB_URI}},

      - run: npm install && npm run test

      # - name: Build docker image
      #   id: docker_build
      #   uses: docker/build
